### ISSUE TITLE
[Enhancement] - Individual sample app README format

### ISSUE THREAD

**Issue by hemchander23** [freshdesk/marketplace-sample-apps#103]
**Description of the enhancement:**
The idea is to have a consistent README for developers who land on sample apps repo. Would require suggestions from all. I have added the format in the issue below

**For which Freshworks product?**
- [x] Freshdesk
- [x] Freshchat
- [x] Freshsales
- [x] Freshservice
- [x] Freshcaller

**Comment by hemchander23** [comment]
# [Sample App Title]

### Description:

_[Description of the sample app]_

### Screenshots:

_[Screenshots that are not too big/small. Gifs are best. Let's just stick to 3 screenshots at the max]_

### Prerequisites:
1. Make sure you have a trial [FreshworksProduct] account created
2. Ensure that you have the Freshworks Developer Kit (FDK) installed properly.

_[From point 3, add some of the important prerequisites which are specific to this app]_

### Procedure to run the app:
1. Fill the `iparam_test_data.json` before running the app locally.
2. Run the app locally using the [`fdk run`](https://developers.freshchat.com/v2/docs/freshworks-cli/#run) command
3. Append `?dev=true` to the Freshworks product URL to see the changes 

_[ Special instructions for realizing the value out of this app]_

Feel free to contribute / raise issues 

----

**Comment by velmurugan-balasubramanian** [comment]
will this order make sense ?
1. Description
2. Prerequisites
3. Procedure to run the app with step by step screenshots/GIFS instead of having it in the beginning
4. GIF of working version of the app.

**Comment by hemchander23** [comment]
Would go with this order as well. Will also add 
*features used in the app*  (data storage/ request / ..)

**Comment by Saif-Shines** [comment]
@hemchander23 
Can we add this template to Contribuiting guidelines as well ?

**Comment by hemchander23** [comment]
Yes Saif

**Comment by Saif-Shines** [comment]
Closing this issue as PR Issue template is created inspired by this work.
