### ISSUE TITLE
[Bug] - Freshdesk Sample CRM App is unable to fetch data from Freshsales API

### ISSUE THREAD

**Issue by prithvijit-dasgupta** [freshdesk/marketplace-sample-apps#105]
**Describe the bug**
The sample_crm_app for Freshdesk fails due to the app using Basic Auth for Freshsales API. Fix is required to access the Freshsales APIs

**Noted in which product sample app**
- [x] Freshdesk
- [ ] Freshchat
- [ ] Freshsales
- [ ] Freshservice
- [ ] Freshcaller

**To Reproduce**
1. Do a 'fdk run' on the sample_crm_app with correctly configured iparams_test_data.json
2. Load your Freshdesk URL with ?dev=true appended to it (https://developers.freshdesk.com/v2/docs/quick-start/)
3. View the 'Ticket Details' page and find the app loaded
4. See error 'Error searching CRM database' as a notification

**Expected behavior**
App should not throw 'Error searching CRM database' with correctly configured test-data

**Browser (please complete the following information):**
Chrome/Safari/ Firefox etc.

**Additional context**
Authentication for Freshsales --> https://www.freshsales.io/api/#intro

**Comment by prithvijit-dasgupta** [comment]
#106 https://github.com/freshdesk/marketplace-sample-apps/pull/106

**Comment by prithvijit-dasgupta** [comment]
#106

**Comment by hemchander23** [comment]
Good catch! Fix tested and merged
