### ISSUE TITLE
[Enhancement] - Solutions/Knowledge base location

### ISSUE THREAD

**Issue by sabatale** [freshdesk/marketplace-sample-apps#168]
**Description of the enhancement:**
Is there any location related to Solutions/Knowledge base?

I've tried something like `kbase-sidebar` but it doesn't seem to be working.

There are also no events related to Solutions either (e.g. When a Solution is added to the conversation by the agent) but I'm guessing that's because Freshdesk itself does offer them at all.

**For which Freshworks product?**
- [ X ] Freshdesk
- [ ] Freshchat
- [ ] Freshsales
- [ ] Freshservice
- [ ] Freshcaller

**Describe the solution you'd like**

![image](https://user-images.githubusercontent.com/50220345/88117840-2d0d6780-cb8a-11ea-9626-989414ce85d0.png)

**Comment by ravirajsubramanian** [comment]
Hi @sabatale,

Thank you for creating this issue to request for a feature request.

This currently does not present in the Freshdesk product app locations and to solve the very use-case. This requires extensible support from Freshdesk to incorporate this feature. It will be implemented later in time as the Freshdesk product team confirmed.

This feedback has already been tracked [here](https://community.developers.freshworks.com/t/908) in [our developer community](https://community.developers.freshworks.com). We will post an update there when this feature is launched.

**Comment by Froglegg** [comment]
Hi @ravirajsubramanian, any update on this feature request?

**Comment by ravirajsubramanian** [comment]
> Hi @ravirajsubramanian, any update on this feature request?

Hi @Froglegg,
There's no update yet on this feedback. Please upvote [the earlier feedback](https://community.developers.freshworks.com/t/programmatically-update-widget-suggested-articles/908) on this topic or create a new feedback topic on our developer forum.
