### ISSUE TITLE
[Enhancement] - Add detailed description for Freshchat sample apps

### ISSUE THREAD

**Issue by hemchander23** [freshdesk/marketplace-sample-apps#38]
**Description of the enhancement:**
Currently, the README for sample apps at https://github.com/freshdesk/marketplace-sample-apps/tree/master/Freshchat is pointing to each sample app. It would be nice to have a short description for each of the sample app there itself.

**For which Freshworks product?**
- [ ] Freshdesk
- [x] Freshchat
- [ ] Freshsales
- [ ] Freshservice
- [ ] Freshcaller

**Comment by sharath2106** [comment]
@hemchander23 I'd like to work on this.

**Comment by ravirajthedeveloper** [comment]
Hello @sharath2106,

Sure, you can try this.
If you need any help, please comment here.

**Comment by sharath2106** [comment]
@ravirajthedeveloper I tried to run the application in my local and it looks like I've to configure using api tokens. Could you please guide me in getting the tokens?

<img width="415" alt="Screenshot 2019-10-21 at 8 13 32 AM" src="https://user-images.githubusercontent.com/25933070/67172884-b2d16c00-f3da-11e9-9f43-4166e08c4769.png">

**Comment by sharath2106** [comment]
@ravirajthedeveloper Could you please help me with the above?

**Comment by sharath2106** [comment]
@ravirajthedeveloper Friendly reminder!

**Comment by ravirajthedeveloper** [comment]
@sharath2106 A short description of the Freshchat apps can be found from the README of each app itself.
If you still would like to run the app, an account in MailChimp can be created with a free plan [here](https://login.mailchimp.com/signup/?plan=free_monthly_plan_v0) and the other details can be fetched from your account.
MailChimp [developer documentation](https://mailchimp.com/developer/guides/get-started-with-mailchimp-api-3/) would be helpful as well.
