### ISSUE TITLE
underscore templates are not working in Autherization_Url

### ISSUE THREAD

**Issue by skhussainbasha** [freshdesk/marketplace-sample-apps#4]
To my freshdesk app, I am Using OAuth based authentication.
My third party API wants to send client_id along with autherization_url like "authorize_url": "https://login.teamviewer.com/oauth2/authorize?response_type=code&client_id=<%= oauth_iparams.client_id %>&redirect_uri=http%3A%2F%2Flocalhost%3A10001%2Fauth%2Fcallback" 
but in freshdesk underscore template doesnot support in "authorize_url". and "token_url";

Can please give me suggestion on how to over come this problem.

**Comment by raghu12133** [comment]
It must work. We do support templating in authorize and token url. Do you get any error while testing?

**Comment by skhussainbasha** [comment]
I don't get any error but when authorizing the app, it's not replaced
iparams.client_id template value so authorization_url does not recognize my
app in third party API which is associated with that client_id.

**Comment by raghu12133** [comment]
Are you using the latest version of the fdk?

**Comment by skhussainbasha** [comment]
Yes, i tried in 4.1.5 and 4.1.7

**Comment by raghu12133** [comment]
Please ensure you have provided authorize_url as [https://login.teamviewer.com/oauth2/authorize](https://login.teamviewer.com/oauth2/authorize) and the token_url as [https://login.teamviewer.com/api/v1/oauth2/token](https://login.teamviewer.com/api/v1/oauth2/token) in oauth_config.json

**Comment by skhussainbasha** [comment]
{
	"client_id": "<%= oauth_iparams.client_id %>",
	"client_secret": "<%= oauth_iparams.client_secret %>",
"authorize_url": "https://login.teamviewer.com/oauth2/authorize?response_type=code&client_id=<%= oauth_iparams.client_id %>&redirect_uri=http%3A%2F%2Flocalhost%3A10001%2Fauth%2Fcallback",
	"token_url": "https://webapi.teamviewer.com/api/v1/oauth2/token",
	"options": {},
	"token_type": "account",
	 "oauth_iparams": {
		"client_id": { 
		  "display_name": "client_id",
		  "description": "Please enter your client_id",
		  "type": "text",
		  "required": true
		},
		"client_secret": { 
		  "display_name": "client_secret",
		  "description": "Please enter your client_secret",
		  "type": "text",
		  "required": true
		}
      }
}

my teamviewer api needs have client_id in authorize_url 
See my API ref:GET login.teamviewer.comoauth2/authorize?response_type=code&client_id=12333-
133Ea4Hdf3e9ec0543fX&redirect_uri=https%3A%2F%2Fclient%2Eexample%2Ecom%2Fcb

**Comment by raghu12133** [comment]
From the configuration that you have provided, it seems like you have used templating in client_id and client_secret which is not supported. Please replace it with actual client_id and client_secret values. The authorize and token URL must be changed to the ones that I have provided.

**Comment by skhussainbasha** [comment]
first point: Then how it will work as dynamic OAuth authentication.You are suggesting me to hard code the client_id and client_secret.I confirmed with you one of your developers he said  "templating only works in client_id and client_secret".
second point: If I replace as suggested then what about the parameter that my API is expecting to have in autherize_url?

**Comment by raghu12133** [comment]
Regarding OAuth, the developer of the app must provide in the client_id and client_secret. The user who installs the app is not expected to provide these credentials.

The parameters that need to be passed through the authorize URI will be taken care by our OAuth authentication system. The parameters that you referred in the documentation is supposed to be provided if the OAuth flow is done manually without a client. In our case all the actions are handled by an OAuth client.

**Comment by skhussainbasha** [comment]
Let me ask the last question.
I have given client_id and client_secret fields if any customer installed my app then how he will provide client_id and client_sercret of his app?

**Comment by raghu12133** [comment]
As i told, the client id and secret must be provided by the developer of the app and not by the user. 

Client ID and secret stand to identify your app(that you have developed) uniquely. And must not be specific to user.

**Comment by skhussainbasha** [comment]
ok thanks.

**Comment by raghu12133** [comment]
Hope it helped. Im closing the issue.
