### ISSUE TITLE
Remove console.log statements

### ISSUE THREAD

**Issue by hemchander23** [freshdesk/marketplace-sample-apps#44]
**Description of the issue:**

The `console.log` statement at line 34 and 114 of app.js has to be removed. 

https://github.com/freshdesk/marketplace-sample-apps/blob/master/Training/fundamentals/level2/app/app.js#L34

https://github.com/freshdesk/marketplace-sample-apps/blob/master/Training/fundamentals/level2/app/app.js#L114

**For which Freshworks product?**
- [x] Freshdesk
- [ ] Freshchat
- [ ] Freshsales
- [ ] Freshservice
- [ ] Freshcaller

**Comment by sammiepls** [comment]
Hi can I work on this?

**Comment by hemchander23** [comment]
Hi @sammiepls, we have already received a PR from @adizz. However, we have more issues coming up. Stay tuned:)!
