### ISSUE TITLE
[Enhancement] - Convert ES6 code to ES5 in a sample app - app.js 

### ISSUE THREAD

**Issue by hemchander23** [freshdesk/marketplace-sample-apps#49]
**Description of the enhancement:**
The code at https://github.com/freshdesk/marketplace-sample-apps/blob/master/Freshdesk/v2/your_first_app/app/app.js contains arrow functions that are not ES5 compliant

**For which Freshworks product?**
- [x] Freshdesk
- [ ] Freshchat
- [ ] Freshsales
- [ ] Freshservice
- [ ] Freshcaller

**Describe the solution you'd like**
The front-end code has to be ES5 compliant.

**Reason**
As a part of mid-market and enterprise move, we might stumble on legacy browsers. It is good to have client-side code in ES5

**Comment by trojano31** [comment]
I can take it

**Comment by ravirajthedeveloper** [comment]
@trojano31 That would be great. Kindly, create a PR and link it to this issue.
Thanks in advance.
