### ISSUE TITLE
[Enhancement] - Remove unused file

### ISSUE THREAD

**Issue by hemchander23** [freshdesk/marketplace-sample-apps#50]
**Description of the enhancement:**
The `handle-response.js` in the `lib` directory is not used. We can remove it

https://github.com/freshdesk/marketplace-sample-apps/tree/master/Freshdesk/v2/your_first_serverless_app/server/

**For which Freshworks product?**
- [x] Freshdesk
- [ ] Freshchat
- [ ] Freshsales
- [ ] Freshservice
- [ ] Freshcaller

**Describe the solution you'd like**
Remove `handle-response.js` at https://github.com/freshdesk/marketplace-sample-apps/tree/master/Freshdesk/v2/your_first_serverless_app/server/lib/

**Comment by danielotieno** [comment]
@hemchander23  I can take this.

**Comment by ravirajthedeveloper** [comment]
@danielotieno That's great. Kindly, give a PR and link it to this issue. Thanks for taking this up.

**Comment by danielotieno** [comment]
@ravirajthedeveloper Awesome. I am working on it
