### ISSUE TITLE
[Feature Request] - Create a sample app to demonstrate the use of Request API to invoke Freshdesk REST APIs

### ISSUE THREAD

**Issue by satwikhebbar** [freshdesk/marketplace-sample-apps#56]
**Describe the sample app use-case :**
The existing sample app - https://github.com/freshdesk/marketplace-sample-apps/tree/master/Freshdesk/v2/simple_request_app - is a good way to learn how to use the Request API feature, but most app developers will end up trying to make Request API calls to Freshdesk. There should be a sample that focuses mainly on this very common use-case.

**For which product ? :**
- [x] Freshdesk
- [ ] Freshchat
- [ ] Freshsales
- [ ] Freshservice
- [ ] Freshcaller

**Do you already have a sample app / PR ready? :**
No

**More details :**
The sample app could have a simple UI that, given a ticket-id, fetches details about the ticket and displays the summary, status and assignee details inline.

**Comment by shravan-balasubramanian** [comment]
I have taken this up. Will come up with a PR soon

**Comment by ravirajthedeveloper** [comment]
@shravan-balasubramanian Thanks for your interest to contribute! 😃

**Comment by hemchander23** [comment]
Thanks @shravan-balasubramanian for the PR. Happy hacktoberfest 🎃 !!
