### ISSUE TITLE
[Feature Request] - Create the first meaningful Freshsales sample app

### ISSUE THREAD

**Issue by satwikhebbar** [freshdesk/marketplace-sample-apps#57]
**Describe the sample app use-case :**
Freshsales has a small quirk (currently) with respect to its Data APIs giving very little information (mainly just an ID) about the entity in question. This means an app must make a REST API to fetch additional details. Freshsales REST APIs are also ever so slightly different. A sample app that fetches details about the current Lead (the page where it loads) and displays basic details - first name, last name, email and city - would be super helpful.

**For which product ? :**
- [ ] Freshdesk
- [ ] Freshchat
- [X] Freshsales
- [ ] Freshservice
- [ ] Freshcaller

**Do you already have a sample app / PR ready? :**
No

**Comment by moniksha-murthy** [comment]
Can I work on this?

**Comment by ravirajthedeveloper** [comment]
Sure and thank you for your interest to contribute. 😃

**Comment by moniksha-murthy** [comment]
https://github.com/freshdesk/marketplace-sample-apps/pull/89

**Comment by hemchander23** [comment]
Thanks, @moniksha-murthy !! Happy Hacktoberfest 🎃
