### ISSUE TITLE
Access token geeting expired in Freshdesk and Freshservice

### ISSUE THREAD

**Issue by skhussainbasha** [freshdesk/marketplace-sample-apps#6]
Hi Raghu,

I am developing zoom app, which uses OAuth feature. access_token is getting expired when the app is idle for some time.

**Comment by raghu12133** [comment]
Zoom has an expiry time for access token as per their docs. And if expired, our Request API must refresh it on behalf. So, are you getting 401 from Request API as status?

**Comment by skhussainbasha** [comment]
yes

**Comment by raghu12133** [comment]
Hey HussainBasha,

We tested zoom's API on our side and the refresh works smoothly when the access token is expired. So, in this case are you missing anything while making the request and do you have the access token in .fdk/localstore file?

**Comment by skhussainbasha** [comment]
as zoom does not accept the local redirect URI, we are testing as the custom app only.

**Comment by hemchander23** [comment]
Hope you were able to solve the issue. Closing the issue. Feel free to create an issue if required.

**Comment by AnithaYerra** [comment]
Hi @raghuram-periaswamy ,
I am also facing same issue in this way i have built one oauth app. if am leaving for some time am getting : ```Response 210 “Accesstoken can’t be refreshed``` so may i know how can i refresh the accesstoken inside the freshdesk authconfig.json

**Comment by ravirajsubramanian** [comment]
Hi @AnithaYerra,

This repository serves only as example codes. Please raise your issue or queries on [our developer forum](community.developers.freshworks.com).
