### ISSUE TITLE
[Enhancement] - twilio sample app - code comments needed

### ISSUE THREAD

**Issue by Saif-Shines** [freshdesk/marketplace-sample-apps#60]
**Description of the enhancement:**
From last few weeks, we started working to add some code comments adhering to [JSDoc standards](https://devhints.io/jsdoc).

**Expectation**
 For example comments as in [this piece of code](https://github.com/freshdesk/marketplace-sample-apps/blob/master/Freshdesk/v2/advanced_data_storage_app/app/js/app.js). 

**Current version**
[Twilio_sms sample app's code](https://github.com/freshdesk/marketplace-sample-apps/blob/master/Freshdesk/v2/twilio_sms/app/app.js) is one of those not yet commented.

**_Would you be interested in understanding the code and giving it a try?_**

**For which Freshworks product?**
- [x] Freshdesk
- [ ] Freshchat
- [ ] Freshsales
- [ ] Freshservice
- [ ] Freshcaller

**Helpful Resources**
1. [Basic app building quick start](https://developers.freshdesk.com/v2/docs/quick-start/).
2. The documentations to [Server method invocation](https://developers.freshdesk.com/v2/docs/server-method-invocation/#invoke) and [Interface API](https://developers.freshdesk.com/v2/docs/interface-api/).

**Comment by sharath2106** [comment]
@Saif-Shines I'd like to work on this.

**Comment by ravirajthedeveloper** [comment]
Hello @sharath2106,

Sure, you can try this. Thanks for coming forward to contribute to our repository.
If you need any help, please comment here.

**Comment by ravirajthedeveloper** [comment]
Hey @sharath2106,

Are you still working on it? If you need any help with it, let us know.

**Comment by prithvijit-dasgupta** [comment]
Hey @sharath2106, if you aren't working on this I would like to raise a PR for this issue.

**Comment by sharath2106** [comment]
@prithvijit-dasgupta I'm working on it. 

@ravirajthedeveloper Was away for a while. You should be receiving a PR tonight. Apologies for the delay!

**Comment by hemchander23** [comment]
Thanks for the contributions @prithvijit-dasgupta @sharath2106 ! Happy Hacktoberfest 🎃 :) !
