### ISSUE TITLE
[Enhancement] - Ticket Top Navigation's app.js to ES5

### ISSUE THREAD

**Issue by Saif-Shines** [freshdesk/marketplace-sample-apps#61]
**Describe**
Even though freshdesk apps run smoothly with ES6 javascript code, to ensure nothing breaks freshdesk recommends app's code to be ES5.

Would you be interested in converting ES6 code to ES5 on T[icket top navigation sample app code](https://github.com/freshdesk/marketplace-sample-apps/blob/master/Freshdesk/v2/ticket_top_navigation_app/app/app.js) ?

**Noted in which product sample app**
- [x] Freshdesk
- [ ] Freshchat
- [ ] Freshsales
- [ ] Freshservice
- [ ] Freshcaller

**Resources**
To ensure running the code after you make changes follow this [quick start.](https://developers.freshdesk.com/v2/docs/quick-start/)

**Comment by Gil707** [comment]
I'll take it

**Comment by hemchander23** [comment]
Thanks! #66 closes this
