### ISSUE TITLE
[Enhancement] - Ticket top navigation app - code comments needed

### ISSUE THREAD

**Issue by Saif-Shines** [freshdesk/marketplace-sample-apps#62]
**Description of the enhancement:**
From last few weeks, we started working to add some code comments adhering to [JSDoc standards](https://devhints.io/jsdoc).

**Expectation**
 For example, comments as in [this piece of code](https://github.com/freshdesk/marketplace-sample-apps/blob/master/Freshdesk/v2/advanced_data_storage_app/app/js/app.js). 

**Current version**
[Ticket Top navigation sample app's code](https://github.com/freshdesk/marketplace-sample-apps/blob/master/Freshdesk/v2/ticket_top_navigation_app/app/app.js) is one of those not yet commented.

**Would you be interested in understanding the code and giving it a try?**

**For which Freshworks product?**
- [x] Freshdesk
- [ ] Freshchat
- [ ] Freshsales
- [ ] Freshservice
- [ ] Freshcaller

**Comment by shonore** [comment]
I can work on this

**Comment by hemchander23** [comment]
Hi @shonore ! Thanks for showing interest ! ♥️ We have a PR for this issue already. However there are other issues still open. :)
