### ISSUE TITLE
[Enhancement] - Sample CRM app -  gifs / screenshots needed

### ISSUE THREAD

**Issue by Saif-Shines** [freshdesk/marketplace-sample-apps#63]
**Description of the enhancement:**
We try adding working gifs or screenshots if a app can be run. But we missed this time adding necessary to [Sample CRM App example](https://github.com/freshdesk/marketplace-sample-apps/tree/master/Freshdesk/v2/sample_crm_app). 

Would you be interested to run the app and add the relevant gifs / screenshots by creating a screenshots folder in the directory?

**For which Freshworks product?**
- [x] Freshdesk
- [ ] Freshchat
- [ ] Freshsales
- [ ] Freshservice
- [ ] Freshcaller

**Resources**
- [How you quick start & run the app?
](https://developers.freshdesk.com/v2/docs/quick-start/#)

**Comment by pragapraga** [comment]
@Saif-Shines I am interested in this but I am facing this error, could you help me in this?
![Screenshot 2019-10-05 at 7 11 51 PM](https://user-images.githubusercontent.com/6701828/66255692-50565a00-e7a4-11e9-943d-d5b42c03dd91.png)

**Comment by hemchander23** [comment]
Hi @pragapraga 

Appreciate the efforts you put in 👏🏻🎉

Just a quick sanity check. Can you check if **config/iparam_test_data.json** is filled? This would be the test data config for the app. In this case, it corresponds to Freshsales CRM trial account credentials. You can find the detailed description of each field in the config descriptor/iparams file **config/iparams.json**

You can read more about them(Installation parameters) over here -> https://developers.freshdesk.com/v2/docs/installation-parameters/

We do have a blog post on this -> https://medium.com/freshworks-developer-blog/securing-sensitive-installation-parameters-3879908ade17

**Comment by hemchander23** [comment]
Hi @pragapraga ! Let me know if you are still working on this :)
