### ISSUE TITLE
[Enhancement] - Convert ES6 to ES5 in the instance_api_app

### ISSUE THREAD

**Issue by hemchander23** [freshdesk/marketplace-sample-apps#64]
**Description of the enhancement:**
We need to convert ES6 code to ES5 in these two javascript files
https://github.com/freshdesk/marketplace-sample-apps/blob/master/Freshdesk/v2/instance_api_app/app/app.js

https://github.com/freshdesk/marketplace-sample-apps/blob/master/Freshdesk/v2/instance_api_app/app/modal.js

**For which Freshworks product?**
- [x] Freshdesk
- [ ] Freshchat
- [ ] Freshsales
- [ ] Freshservice
- [ ] Freshcaller

**Describe the solution you'd like**
**let** keyword, **=>** arrow functions, etc are part of ES6. The code in the above-mentioned scripts is not ES5 compliant. This needs to be modified to be ES5 compliant

**Reason**
We want to extend our support of sample apps to legacy browsers as it will be used by mid-market and enterprise customers as well.

Please follow the [contributing guidelines](https://github.com/freshdesk/marketplace-sample-apps/blob/master/CONTRIBUTING.MD) before raising the PR :) !!

Happy Hacking! 🎃♥️

**Comment by Akshay-911** [comment]
I can go for this issue.

**Comment by hemchander23** [comment]
Hi @Akshay-911 ! We have a PR for this issue already. But hey, we have couple of other issues open!

**Comment by Akshay-911** [comment]
Alright, but I think using a web pack like babel will be a better option, In that case code will become scalable.

**Comment by hemchander23** [comment]
That's right @Akshay-911! The idea is to have simple ES5 compliant boilerplates to start with.
