### ISSUE TITLE
[Enhancement] -github_issues_external_events_app (Training) - Add documentation links for each platform feature used in the readme file

### ISSUE THREAD

**Issue by ravirajthedeveloper** [freshdesk/marketplace-sample-apps#68]
**Description of the enhancement:**
It's a request for a change in the readme file for an existing app.
In the readme file of the [GitHub Issues external events app](https://github.com/freshdesk/marketplace-sample-apps/tree/master/Training/github_issues_external_events_app), there is a list of platform features mentioned which have been used in the app. It would be nice to add links to these features listed with the relevant feature's link from our developer documentation.

**Note:**
* Adding links only to the platform features is enough
* Add the link of the [Installation parameter section](https://developer.freshdesk.com/v2/docs/installation-parameters/) from the documentation for the _secure installation parameter_ platform feature in the list.

**For which Freshworks product?**
- [x] Freshdesk
- [ ] Freshchat
- [ ] Freshsales
- [ ] Freshservice
- [ ] Freshcaller

**Resources**
* [Developer documentation](https://developer.freshdesk.com/v2/docs/quick-start)

**Comment by wukrit** [comment]
I'd like to take up this issue

**Comment by hemchander23** [comment]
That's amazing @wukrit ! Give it a try 🎉

**Comment by hemchander23** [comment]
That's amazing @wukrit! Please feel free to pick it up 🎉

**Comment by ravirajthedeveloper** [comment]
Hello @wukrit, Thanks for your contribution!
Keep looking at this repo for more requests. 😃 

Happy Hacktoberfest! 🎉
