### ISSUE TITLE
[Enhancement] - Onclick alerts app - Freshservice - JSDoc standards required

### ISSUE THREAD

**Issue by Saif-Shines** [freshdesk/marketplace-sample-apps#91]
**Description of the enhancement:**
The Freshservice app called [Onclick_alerts](https://github.com/freshdesk/marketplace-sample-apps/tree/master/Freshservice/onclick_alerts) is built over an year ago.

Can you Refactor it in a way that it has enough code comments? (Sample [commented code](https://github.com/freshdesk/marketplace-sample-apps/blob/master/Freshdesk/v2/advanced_data_storage_app/app/js/app.js))

**For which Freshworks product?**
- [ ] Freshdesk
- [ ] Freshchat
- [ ] Freshsales
- [x] Freshservice
- [ ] Freshcaller

**Comment by nithin-nayagam** [comment]
@Saif-Shines I'd like to take this up. Will send a PR soon.

**Comment by hemchander23** [comment]
Thanks for the contribution @nithin-nayagam ! Happy hacktoberfest 🎃 !
