### ISSUE TITLE
[Bug] - Coverage folder accidentally added

### ISSUE THREAD

**Issue by Saif-Shines** [freshdesk/marketplace-sample-apps#92]
**Description of the enhancement:**
In the [show_ticket_and_associated_details sample app](https://github.com/freshdesk/marketplace-sample-apps/tree/master/Freshservice/show_ticket_and_associated_details), the coverage folder is accidentally added in the directory which is not needed in the scope of sample apps repo.

Will you be able to remove it?

**For which Freshworks product?**
- [ ] Freshdesk
- [ ] Freshchat
- [ ] Freshsales
- [x] Freshservice
- [ ] Freshcaller

**Comment by theparselmouth** [comment]
will take this up
