### ISSUE TITLE
[Enhancement] - Readme file needed 

### ISSUE THREAD

**Issue by Saif-Shines** [freshdesk/marketplace-sample-apps#93]
**Description of the enhancement:**
The freshservice [github workflow actions app](https://github.com/freshdesk/marketplace-sample-apps/tree/master/Freshservice/github_workflow_actions) currently doesn't have a Readme.md file.

Would you be interested to learn about it and add a Readme.md file?

**For which Freshworks product?**
- [ ] Freshdesk
- [ ] Freshchat
- [ ] Freshsales
- [x] Freshservice
- [ ] Freshcaller

**Comment by HarisSpahija** [comment]
Hey Saif, I would love to pick up this issue! Can you give me an example of what you want the README to look like?

**Comment by Saif-Shines** [comment]
Hi @HarisSpahija ,
Thank you for your participation interest.
Here are the things that we are looking for in a Readme.md file

- What are workflow actions and what problems will it solve
- Brief steps upon how they can build their own
- Read this [Blogpost](https://medium.com/freshworks-developer-blog/build-workflow-actions-to-extend-automations-in-freshworks-b7cbe8758c5b) to understand this better.

**Comment by hemchander23** [comment]
Hi @HarisSpahija ! Thanks for showing interest 🙂Let me know if you are working on it

**Comment by HarisSpahija** [comment]
I have not yet @hemchander23 , feel free to pick this issue up!
