### ISSUE TITLE
[Enhancement] - v1 README should clearly call out this version is no longer supported

### ISSUE THREAD

**Issue by satwikhebbar** [freshdesk/marketplace-sample-apps#98]
**Description of the enhancement:**
The README should state in BOLD terms we do not support this version of the platform anymore. In addition, all READMEs of all sample apps in this folder must state the same.

**For which Freshworks product?**
- [X] Freshdesk
- [ ] Freshchat
- [ ] Freshsales
- [ ] Freshservice
- [ ] Freshcaller

**Describe the solution you'd like**
Same as described above.

**Comment by EmadBinAbid** [comment]
I am working on this issue. Will be generating a PR soon.

**Comment by hemchander23** [comment]
Thanks, @EmadBinAbid ! One of our maintainers will review this soon.
